/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#e0e3e5',
        'surface-bright': '#f7f9fb',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#004395',
        'on-background': '#191c1e',
        'on-surface': '#191c1e',
        'on-secondary-fixed-variant': '#3f465c',
        primary: '#006c49',
        'surface-container-low': '#f2f4f6',
        'surface-tint': '#006c49',
        'secondary-fixed-dim': '#bec6e0',
        'surface-container-high': '#e6e8ea',
        'surface-dim': '#d8dadc',
        'primary-container': '#10b981',
        'tertiary-container': '#71a1ff',
        error: '#ba1a1a',
        'secondary-container': '#dae2fd',
        tertiary: '#005ac2',
        'on-tertiary-fixed': '#001a42',
        'primary-fixed-dim': '#4edea3',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#eff1f3',
        surface: '#f7f9fb',
        'surface-container': '#eceef0',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#00367a',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#adc6ff',
        'surface-container-highest': '#e0e3e5',
        'on-primary-fixed': '#002113',
        'on-secondary-container': '#5c647a',
        secondary: '#565e74',
        'outline-variant': '#bbcabf',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#005236',
        'secondary-fixed': '#dae2fd',
        'on-surface-variant': '#3c4a42',
        'on-secondary-fixed': '#131b2e',
        background: '#f7f9fb',
        outline: '#6c7a71',
        'tertiary-fixed': '#d8e2ff',
        'on-primary-container': '#00422b',
        'inverse-surface': '#2d3133',
        'primary-fixed': '#6ffbbe',
        'inverse-primary': '#4edea3',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans'],
        body: ['Manrope'],
        label: ['Manrope'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
